services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes: [mongo_data:/data/db]
    ports: ["27017:27017"]

  auth:
    build: ./services/auth-service
    environment:
      PORT: 4001
      MONGO_URL: mongodb://mongo:27017/novabank_auth
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET:-change-this-in-production}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      MAIL_FROM: ${MAIL_FROM:-NovaBank <no-reply@example.com>}
      ACCOUNTS_URL: http://accounts:4002
    depends_on: [mongo, accounts]

  accounts:
    build: ./services/accounts-service
    environment:
      PORT: 4002
      MONGO_URL: mongodb://mongo:27017/novabank_accounts
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET:-change-this-in-production}
    depends_on: [mongo]

  transactions:
    build: ./services/transactions-service
    environment:
      PORT: 4003
      MONGO_URL: mongodb://mongo:27017/novabank_transactions
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET:-change-this-in-production}
      AUTH_URL: http://auth:4001
      ACCOUNTS_URL: http://accounts:4002
    depends_on: [mongo, auth, accounts]

  frontend:
    build: ./frontend
    ports: ["5173:80"]
    depends_on: [auth, accounts, transactions]

volumes:
  mongo_data:
